title:  Delfino Restoration Work Party Decebmer 31, 2018
lat:   47.5556428
lon:  -122.2534164
firstReported: 2018-12-31
lastUpdate:
radius:  10
area: 10
severity: 10
notesFile: notes.html
videoTabs:
   - title: "video"
     url: https://www.youtube.com/embed/HjWZvWCZITE?rel=0




