area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 8-16, 2018
lastUpdate: 8-16, 2018
lat: 47.5268573
lon: -122.0041685
notesFile: ''
radius: 10.0
severity: 2
text: 80 plus dead to this point. tiger mountain
title: 'traditionlake trail: 80 plus dead to this point.'
type: rectangle
