area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.59576430660447
lon: -122.1675566630037
notesFile: notes.html
radius: 100
severity: 0
text: 20 plus dead ln area. 2 or 3 previously- October 13, 2017. Al Smith Field Report
  19
title: increasing deaths over time
type: simple
