area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 12-14, 2018
lastUpdate: 12-14, 2018
lat: 47.5580861
lon: -122.3745666
notesFile: ''
radius: 10.0
severity: 1
text: some restoration work. many sickly looking but fewer dead along 200 feet or
  so of trail. seattle
title: 'camp long: some restoration work. many sickly looking but fewer dead along
  200 feet or so of trail.'
type: rectangle
