area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 9-15,2018
lastUpdate: 9-15,2018
lat: 47.5189277
lon: -122.1612755
notesFile: ''
radius: 10.0
severity: 2
text: more dead and dying since last time.about 40 in first 400 feet newcastle
title: 'may creek: more dead and dying since last time.about 40 in first 400 feet'
type: rectangle
