area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 5-05, 2019
lastUpdate: 5-05, 2019
lat: 47.6282164
lon: -122.2963621
notesFile: ''
radius: 10.0
severity: 2
text: 20+ dead in area restoration site seattle west of parking lot
title: 'arbotetum: 20+ dead in area restoration site'
type: rectangle
