area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 1-10, 2019
lastUpdate: 1-10, 2019
lat: 47.5423281
lon: -122.0803769
notesFile: ''
radius: 10.0
severity: 2
text: about 20 dead scattered to this point. thorough brushwacking along trails killing
  off sword ferns makes count difficult. about 7 dead or dying at this surprise lake
  trail
title: 'cougar mountain: about 20 dead scattered to this point. thorough brushwacking
  along trails killing off sword ferns makes count difficult. about 7 dead or dying
  at this'
type: rectangle
