default: restoration

restoration:
	(cd ..; python regen.py singleFernWatch singleFernWatch/singleFernWatch.html)

publish:
	scp singleFernWatch.html paulshannnon@pshannon.net:public_html/pshannon.net/maps/
	open http://pshannon.net/maps/singleFernWatch.html


