area: 10
color: orange
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.561372
lon: -122.297552
notesFile: notes.html
radius: 100
severity: 0
text: 'Observed 2017: a young forest, no evergreens, ~100 dead ferns counted, ecological
  impact maybe minor'
title: Cheasty Moutain view
type: simple
