area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 11-17, 2018
lastUpdate: 11-17, 2018
lat: 47.5041677
lon: -122.0910808
notesFile: ''
radius: 10.0
severity: 1
text: 8 or so dead in area. another 20 or so scattered along .1 mile trail to redtown
  dam. cave hole trail
title: 'cougar mountain: 8 or so dead in area. another 20 or so scattered along .1
  mile trail to redtown dam.'
type: rectangle
