default:
	python ../regen.py . regional.2020_alSmith.html
	open regional.2020_alSmith.html
venv:
	@echo source /Users/paul/github/slexil/tests/pshannon-py363/bin/activate

publish:
	scp regional.2020_alSmith.html paulshannnon@pshannon.net:public_html/pshannon.net/swordFerns/regionalMap/2020_alSmith.html
	open http://pshannon.net/swordFerns/regionalMap/2020_alSmith.html

