area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 3-07, 2018
lastUpdate: 3-07, 2018
lat: 47.531538
lon: -122.3967895
notesFile: ''
radius: 10.0
severity: 2
text: 25 plus dead. some just stubble covered with moss. seattle
title: 'lincoln: 25 plus dead. some just stubble covered with moss.'
type: rectangle
