area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.7464
lon: -122.50578
notesFile: notes.html
radius: 100
severity: 0
text: 'February, 2019: dead ferns, reported by John Oleary'
title: IPT2
type: simple
