area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.51892203321663
lon: -122.1612607665263
notesFile: notes.html
radius: 100
severity: 0
text: more dead and dying since last time.about 40 in first 400 feet. Al Smith Field
  Report 25
title: increasing deaths over time
type: simple
