area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.60517848027934
lon: -122.1783172008675
notesFile: notes.html
radius: 100
severity: 0
text: many dead along gravel road. 30+? Al Smith Field Report 61
title: along gravel road
type: simple
