area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.51883581140758
lon: -122.160909187541
notesFile: notes.html
radius: 100
severity: 0
text: about ten dead Al Smith Field Report 2
title: About 10 dead ferns
type: simple
