area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 1-26, 2019
lastUpdate: 1-26, 2019
lat: 47.5565507
lon: -122.1666091
notesFile: ''
radius: 10.0
severity: 1
text: eight dead in immediate area + some looking quite sickly. lots of ivy and removed
  some in a few pictures "Bellevue, north section of trail just west of coal creek
  parkway"
title: 'coal creek park: eight dead in immediate area + some looking quite sickly.
  lots of ivy and removed some in a few pictures'
type: rectangle
