area: 10
color: orange
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.527943
lon: -122.2628
notesFile: notes.html
radius: 100
severity: 0
text: 1/4 acre, new in winter of 2018
title: Pritchard Beach
type: simple
