area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 9-27,2017
lastUpdate: 9-27,2017
lat: 47.5926816
lon: -122.1142602
notesFile: ''
radius: 10.0
severity: 1
text: '"s, w" '
title: 'weowema park: s, w'
type: rectangle
