area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 9-27,2017
lastUpdate: 9-27,2017
lat: 47.5928916
lon: -122.1152473
notesFile: ''
radius: 10.0
severity: 2
text: '"n, se" '
title: 'weowena park: n, se'
type: rectangle
