area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.58291193160579
lon: -122.2252119684736
notesFile: notes.html
radius: 100
severity: 0
text: about 25 dead. jumped over the ridge and into east ravine. few reduced to stubble
  as of now. Al Smith Field Report 28
title: 25 dead
type: simple
