area: 1
color: red
contact: Caleb Goldstein-Miller
firstReported: '2019-06-26'
lastUpdate: '2019-06-26'
lat: 47.523645
lon: -121.467627
notesFile: notes.html
radius: 400
severity: 5
text: 
title: Snoqualmie River (SRD2)
type: simple



