title:  Fort Ward and Blakely Harbor Parks, with connecting trail
lat: 47.595072
lon: -122.522760
firstReported: 2017-08-23
lastUpdate:  2019-03-28
radius:  100
area: 10
severity: 10
notesFile: notes.html
photoTabs:
  - title: "8/17"
    url: https://lh3.googleusercontent.com/qZWlMebh78j-0DKaLBnuQOn2pXyEukvPA7MqkMeMuO0r3nFTefzZ7Re9Ya9gv5VIu3LpiLr4AWVO4VVg1KKTvO1RWzXf3MLy5CJQ6ObBfIknAcczu75WhSTa0Qd4f46dCSY-Ih5CTGs=w2400
videoTabs:
   - title: "1/19"
     url: https://www.youtube.com/embed/bFWLWprsUwA?rel=0






