area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-27, 2018
lastUpdate: 10-27, 2018
lat: 47.5518643
lon: -122.1539048
notesFile: ''
radius: 10.0
severity: 2
text: 20 or more dead in area. along the trail others looking sickly. bellevue
title: 'westwood-highland park: 20 or more dead in area. along the trail others looking
  sickly.'
type: rectangle
