area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: september 1, 2019
lastUpdate: september 1, 2019
lat: 47.5443692
lon: -122.2148166
notesFile: ''
radius: 10.0
severity: 1
text: 17deadfernsq towards east mercer way. mercer island
title: 'engstrom preserve: 17deadfernsq towards east mercer way.'
type: rectangle
