area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 9-14, 2018
lastUpdate: 9-14, 2018
lat: 47.5634368
lon: -122.3008751
notesFile: ''
radius: 10.0
severity: 2
text: '30 plus dead over couple hundred feet by fifty feet. '
title: 'cheasty. boulevard: 30 plus dead over couple hundred feet by fifty feet.'
type: rectangle
