area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.52434130747578
lon: -122.0235095737103
notesFile: notes.html
radius: 100
severity: 0
text: trail to round lake, hopefully. about 8t0 dead so far. Al Smith Field Report
  12
title: trail to Round lake
type: simple
