area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 9/13/17
lastUpdate: 9/13/17
lat: 47.5554269
lon: -122.2495391
notesFile: ''
radius: 10.0
severity: 3
text: 'Ground Zero '
title: 'seward: Ground Zero'
type: rectangle
