area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: august18, 2019
lastUpdate: august18, 2019
lat: 47.5918764
lon: -122.2270354
notesFile: ''
radius: 10.0
severity: 1
text: 40 dead. no more seem to stressed or dying. some other than 40 are little more
  than stubble but displaying new growth. dead all planted ? mercer island
title: 'luther burbank: 40 dead. no more seem to stressed or dying. some other than
  40 are little more than stubble but displaying new growth. dead all planted ?'
type: rectangle
