area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.54232242054441
lon: -122.0803621603057
notesFile: notes.html
radius: 100
severity: 0
text: about 20 dead scattered to this point. thorough brushwacking along trails killing
  off sword ferns makes count difficult. about 7 dead or dying at this. Al Smith Field
  Report 64
title: 20 dead
type: simple
