area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.53193564847363
lon: -122.0140818983697
notesFile: notes.html
radius: 100
severity: 0
text: about 20 dead in area. Al Smith Field Report 6
title: approx. 20 dead
type: simple
