area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.53153234711719
lon: -122.3967746389856
notesFile: notes.html
radius: 100
severity: 0
text: 25 plus dead. some just stubble covered with moss. Al Smith Field Report 3
title: '>25 dead'
type: simple
