area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: august 30, 2019
lastUpdate: august 30, 2019
lat: 47.5522777
lon: -122.2147539
notesFile: ''
radius: 10.0
severity: 1
text: '"2 or more dead ferns, but also some have at least touch of a sickly yellowish
  green color." mercer island'
title: 'parkwood ridge open space: 2 or more dead ferns, but also some have at least
  touch of a sickly yellowish green color.'
type: rectangle
