area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-12, 2018
lastUpdate: 10-12, 2018
lat: 47.5314271
lon: -121.9986403
notesFile: ''
radius: 10.0
severity: 3
text: 'photos left-right every 10 or so i.e. 3 paces for 100''. '
title: 'swamp trail, tiger mountain: photos left-right every 10 or so i.e. 3 paces
  for 100.'
type: rectangle
