area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 6/28/17
lastUpdate: 6/28/17
lat: 47.5614561
lon: -122.2976832
notesFile: ''
radius: 10.0
severity: 1
text: ' "4701 Mountain View Dr S, Seattle, WA 98108"'
title: 'Cheasty Mt View: '
type: rectangle
