area: 10
color: red
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.701276
lon: -122.583528
notesFile: notes.html
radius: 100
severity: 0
text: Two acres, private second-growth forest, first regional report 2010
title: Sandy Hook Road
type: simple
