area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-20, 2018
lastUpdate: 10-20, 2018
lat: 47.507169
lon: -122.0828101
notesFile: ''
radius: 10.0
severity: 3
text: '183 dead to this point. going home '
title: 'Sauk mountain: 183 dead to this point. going home'
type: rectangle
