area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 9-26,2017
lastUpdate: 9-26,2017
lat: 47.5637025
lon: -122.3003187
notesFile: ''
radius: 10.0
severity: 1
text: '"nw, sw" '
title: 'cheasty: nw, sw'
type: rectangle
