area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.56373053646463
lon: -122.2996924001585
notesFile: notes.html
radius: 100
severity: 0
text: 45+ dead along a couple hundred feet of trail and 30 feet to either side. many
  more, perhaps a quarter more appear to be dying. Al Smith Field Report 62
title: '>45 dead along trail'
type: simple
