area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-20, 2018,
lastUpdate: 10-20, 2018,
lat: 47.5061573
lon: -122.0855889
notesFile: ''
radius: 10.0
severity: 2
text: '"35 dead along road to just a little beyond this point.some back up in woods,
  59+ dead so far." cougar squak corridor'
title: 'Sauk mountain: 35 dead along road to just a little beyond this point.some
  back up in woods, 59+ dead so far.'
type: rectangle
