area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-20, 2018
lastUpdate: 10-20, 2018
lat: 47.5141817
lon: -122.0894937
notesFile: ''
radius: 10.0
severity: 1
text: 'about 10 dead in area. 114 dead counted along connector trail. '
title: 'Sauk mountain connector: about 10 dead in area. 114 dead counted along connector
  trail.'
type: rectangle
