area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.5310510721141
lon: -121.99829576361
notesFile: notes.html
radius: 100
severity: 0
text: 50 plus dead, Al Smith Field Report 8
title: '>50 dead'
type: simple
