area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 12-21 2018
lastUpdate: 12-21 2018
lat: 47.6051842
lon: -122.178332
notesFile: ''
radius: 10.0
severity: 1
text: many dead along gravel road. 30+? bellevue
title: 'wilburton park se 5th street: many dead along gravel road. 30+?'
type: rectangle
