area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 6-02, 2018
lastUpdate: 6-02, 2018
lat: 47.5289546
lon: -122.0215669
notesFile: ''
radius: 10.0
severity: 1
text: '"about  15 dead to this point, but another20dead in immediate area." issaquah'
title: 'tiger mountain. tradition plateau: about  15 dead to this point, but another20dead
  in immediate area.'
type: rectangle
