area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.56182530797623
lon: -122.2511786322254
notesFile: notes.html
radius: 100
severity: 0
text: I found three dead  2014. shannon took video jan or thereabouts 50 dead. now
  100 plus. original dead site almost bereft of buttercup, Al Smith Field Report 4
title: increasing die off since 2014
type: simple
