area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 8-03,2018
lastUpdate: 8-03,2018
lat: 47.3661034
lon: -122.1396986
notesFile: ''
radius: 10.0
severity: 2
text: '30 plus dead  sword ferns.just a coupl '
title: 'soos creek: 30 plus dead  sword ferns.just a coupl'
type: rectangle
