area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: august 16, 2018
lastUpdate: august 16, 2018
lat: 47.5958464
lon: -122.1675582
notesFile: ''
radius: 10.0
severity: 1
text: '"20 plus dead in area, 2 or 3 dead previously." mctavish'
title: 'bellevue: 20 plus dead in area, 2 or 3 dead previously.'
type: rectangle
