area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 21-21, 2018
lastUpdate: 21-21, 2018
lat: 47.6054894
lon: -122.1770332
notesFile: ''
radius: 10.0
severity: 2
text: '"Alex Wright, botanist was aware of the off in garden and wilburton hill before
  I took first photopoint. many dead elsewhere in the garden." '
title: 'Bellevue botanical garden: Alex Wright, botanist was aware of the off in garden
  and wilburton hill before I took first photopoint. many dead elsewhere in the garden.'
type: rectangle
