area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.36902340299372
lon: -122.1381059414106
notesFile: notes.html
radius: 100
severity: 0
text: another 20 dead or so on other side, east side of trail. Al Smith Field Report
  36
title: 20 dead
type: simple
