area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: july 18,2018
lastUpdate: july 18,2018
lat: 47.6966828
lon: -122.0517669
notesFile: ''
radius: 10.0
severity: 1
text: '30 dead or so at beginning of trail.116 dead trout loop trail '
title: 'redmond watershed preserve: 30 dead or so at beginning of trail.116 dead trout
  loop trail'
type: rectangle
