area: 10
color: red
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.94537
lon: -122.69209
notesFile: notes.html
radius: 100
severity: 0
text: First seen in 2010, now covers 1+ acres, actively spreading
title: Port Ludlow North
type: simple
