area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.69595
lon: -122.59327
notesFile: notes.html
radius: 100
severity: 0
text: 'February, 2019: dead ferns, reported by John Oleary'
title: SHW
type: simple
