area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-04,2017
lastUpdate: 10-04,2017
lat: 47.6113482
lon: -122.2834849
notesFile: ''
radius: 10.0
severity: 1
text: '"se, sw" '
title: 'madrona woods: se, sw'
type: rectangle
