area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-07, 2018
lastUpdate: 10-07, 2018
lat: 47.5918857
lon: -122.2271501
notesFile: ''
radius: 10.0
severity: 1
text: about 20 dead in area. maybe planted. mercer island
title: 'luther burbank park: about 20 dead in area. maybe planted.'
type: rectangle
