area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.60341058683053
lon: -122.1126027132392
notesFile: notes.html
radius: 100
severity: 0
text: about 84 dead in area. so far 2 big areas of die-off, 2 smaller areas of less
  than 20 dead each and some scattered adding to about 250 dead. Al Smith Field Report
  34
title: 84 dead
type: simple
