area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-12,2018
lastUpdate: 10-12,2018
lat: 47.5349078
lon: -122.0133662
notesFile: ''
radius: 10.0
severity: 2
text: 50+ dead sword ferns along and about 50' of trail. "tiger mountain, issaquah"
title: 'Brink trail: 50+ dead sword ferns along and about 50 of trail.'
type: rectangle
