area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.61126073303547
lon: -122.2835073339808
notesFile: notes.html
radius: 100
severity: 0
text: 15 or so dead within 50 uptrail and downstream. Al Smith Field Report 22
title: 15 plus 50 up trail
type: simple
