area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 11-09, 2018
lastUpdate: 11-09, 2018
lat: 47.5587555
lon: -122.2482876
notesFile: ''
radius: 10.0
severity: 1
text: skunk cabbage patch looks more robust compared to southern patch. also north
  patch has no dead sword ferns. north skunk cabbage patch
title: 'Seward park: skunk cabbage patch looks more robust compared to southern patch.
  also north patch has no dead sword ferns.'
type: rectangle
