area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: ''
lastUpdate: ''
lat: 47.5311954
lon: -121.9983978
notesFile: ''
radius: 10.0
severity: 3
text: '122 dead counted from trail in just 100''.'' '
title: 'same as 5sw: 122 dead counted from trail in just 100.'
type: rectangle
