area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 9-24, 2019
lastUpdate: 9-24, 2019
lat: 47.6021316
lon: -121.9821041
notesFile: ''
radius: 10.0
severity: 1
text: counted about  20 dead in area but probably many more hidden by trailing blackberry.
  blue jay way
title: 'soaring eagle  - 30 acres park.  issaquah highland: counted about  20 dead
  in area but probably many more hidden by trailing blackberry.'
type: rectangle
