area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 9-29,2017
lastUpdate: 9-29,2017
lat: 47.5064993
lon: -122.0860014
notesFile: ''
radius: 10.0
severity: 1
text: 'ne '
title: 'squak: ne'
type: rectangle
