area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 1-10, 2019
lastUpdate: 1-10, 2019
lat: 47.545766
lon: -122.0743818
notesFile: ''
radius: 10.0
severity: 1
text: '"counted 8 dead may 18, 2018 up to shangra la trail. obviously missed seeing
  these 16. + crowns and stubble covered with moss." big tree ridge trail'
title: 'cougar mountain: counted 8 dead may 18, 2018 up to shangra la trail. obviously
  missed seeing these 16. + crowns and stubble covered with moss.'
type: rectangle
