area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-19, 2018
lastUpdate: 10-19, 2018
lat: 47.6439875
lon: -122.0524789
notesFile: ''
radius: 10.0
severity: 1
text: about 15 dead in area sammamish
title: 'Evans creek preserve: about 15 dead in area'
type: rectangle
