area: 1
color: red
contact: Caleb Goldstein-Miller
firstReported: '2019-06-17'
lastUpdate: '2019-06-17'
lat: 47.41317
lon: -123.30788
notesFile: notes.html
radius: 400
severity: 5
text: Large site, very remote, survivors are mostly along creek bank that cuts through site.
title: FS210 (Near Brown Creek Campground)
type: simple



