area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-27,2018
lastUpdate: 10-27,2018
lat: 47.5520693
lon: -122.1488726
notesFile: ''
radius: 10.0
severity: 2
text: 106 dead .5 mile length of trail. some might have been planted as perhaps the
  7+ dead at this point. bellevue?
title: 'westwood-highland park: 106 dead .5 mile length of trail. some might have
  been planted as perhaps the 7+ dead at this point.'
type: rectangle
