area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-17, 2018
lastUpdate: 10-17, 2018
lat: 47.5277207
lon: -122.0670279
notesFile: ''
radius: 10.0
severity: 2
text: 25 or so dead in area. 247 or so dead before intersection of bear ridge trail
  with west tibbets creek trail. bear ridge trail
title: 'cougar-talus slope: 25 or so dead in area. 247 or so dead before intersection
  of bear ridge trail with west tibbets creek trail.'
type: rectangle
