area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 5-03, 2019
lastUpdate: 5-03, 2019
lat: 47.5365762
lon: -121.9919826
notesFile: ''
radius: 10.0
severity: 2
text: '"20+ dead at this point and 170 dead counted on 2 trails, so far.south pond
  trailhead tohigh point trailhead 315 + dead." grand ridge trail'
title: 'issaquah highlands: 20+ dead at this point and 170 dead counted on 2 trails,
  so far.south pond trailhead tohigh point trailhead 315 + dead.'
type: rectangle
