area: 1
color: red
contact: Caleb Goldstein-Miller
firstReported: '2019-06-05'
lastUpdate: '2019-06-05'
lat: 47.697997
lon: -122.051710
notesFile: notes.html
radius: 400
severity: 5
text: just north of the parking lot trail
title: Redmond Watershed Preserve Die-off 1
type: simple



