area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.51462274168978
lon: -122.0838484918956
notesFile: notes.html
radius: 100
severity: 0
text: 114 dead or more along length of trail. a couple areas of ten or more. Al Smith
  Field Report 44
title: 114 dead
type: simple
