area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 9-27, 2017
lastUpdate: 9-27, 2017
lat: 47.5418914
lon: -122.1509388
notesFile: ''
radius: 10.0
severity: 2
text: '"se, e" '
title: 'Coal Creek: se, e'
type: rectangle
