area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 11-13, 2018
lastUpdate: 11-13, 2018
lat: 47.5609038
lon: -122.2541201
notesFile: ''
radius: 10.0
severity: 1
text: knapsack in middle of 4 dead stubble sword ferns first noticed in 2014. north
  end of Bailey peninsula
title: 'Seward park: knapsack in middle of 4 dead stubble sword ferns first noticed
  in 2014.'
type: rectangle
