area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 5-05,2018
lastUpdate: 5-05,2018
lat: 47.561831
lon: -122.2511934
notesFile: ''
radius: 10.0
severity: 1
text: '"I found three dead  2014. shannon took video jan or thereabouts 50 dead. now
  100 plus.originaldead site almost bereft of buttercup ," '
title: 'sedward: I found three dead  2014. shannon took video jan or thereabouts 50
  dead. now 100 plus.originaldead site almost bereft of buttercup ,'
type: rectangle
