area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: march 11, 2019
lastUpdate: march 11, 2019
lat: 47.5974912
lon: -122.51722
notesFile: ''
radius: 10.0
severity: 2
text: very rough count of 60+ dead. photo displays maybe 1 dead but some looking quite
  sad. bainbridge island
title: 'blakely harbor: very rough count of 60+ dead. photo displays maybe 1 dead
  but some looking quite sad.'
type: rectangle
