area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: august 19, 2019
lastUpdate: august 19, 2019
lat: 47.583166
lon: -122.2259156
notesFile: ''
radius: 10.0
severity: 2
text: '"80+ dead west slope, picture shows 2 sickly looking ferns of which none were
  seen so yellowish green in luther burbank park among 60 or so dead." mercer island'
title: 'upper luther burbank park: 80+ dead west slope, picture shows 2 sickly looking
  ferns of which none were seen so yellowish green in luther burbank park among 60
  or so dead.'
type: rectangle
