area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.53099585467476
lon: -122.0064129672695
notesFile: notes.html
radius: 100
severity: 0
text: bunch of dead above trail. 50? plus along swamp trail. Al Smith Field Report
  7
title: Die off above trail
type: simple
