area: 1
color: red
borderColor: red
contact: Caleb Goldstein-Miller
firstReported: '2019-08-01'
lastUpdate: '2019-08-01'
lat: 44.78005
lon: -122.57940
notesFile: notes.html
radius: 400
severity: 1
text: In a grove of large cedars. Originally reported by Al Smith?
title: Osprey Road, Marion County OR
type: circle



