area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 1-28, 2019
lastUpdate: 1-28, 2019
lat: 47.705241
lon: -122.0509869
notesFile: ''
radius: 10.0
severity: 2
text: August 2018 a few dead at this site. now over 30 dead plus others not looking
  so good. pipeline connector trail
title: 'Redmond watershed preserve: August 2018 a few dead at this site. now over
  30 dead plus others not looking so good.'
type: rectangle
