area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.55206360296923
lon: -122.1488578333033
notesFile: notes.html
radius: 100
severity: 0
text: 106 dead .5 mile length of trail. some might have been planted as perhaps the
  7+ dead at this point. Al Smith Field Report 48
title: 106 dead
type: simple
