area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 4-30, 2019
lastUpdate: 4-30, 2019
lat: 47.6289683
lon: -122.2975711
notesFile: ''
radius: 10.0
severity: 2
text: '"about 70 dead in restoration project, most dead planted?" "seattle, along
  28th ave e"'
title: 'arboretum: about 70 dead in restoration project, most dead planted?'
type: rectangle
