area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 11-24, 2018
lastUpdate: 11-24, 2018
lat: 47.6511961
lon: -122.1654528
notesFile: ''
radius: 10.0
severity: 1
text: 'about 10 dead in area. same place as previous photopoint? '
title: 'bridal trails: about 10 dead in area. same place as previous photopoint?'
type: rectangle
