area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 4-30, 2019
lastUpdate: 4-30, 2019
lat: 47.611344
lon: -122.2835489
notesFile: ''
radius: 10.0
severity: 2
text: 20+ dead 30' up hill seattle
title: 'madrona woods: 20+ dead 30 up hill'
type: rectangle
