area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.55792134232509
lon: -122.3742091893552
notesFile: notes.html
radius: 100
severity: 0
text: a few dead along 100 feet of trail, but 15 more near dead. Al Smith Field Report
  27
title: a few along trail, +15 nearby
type: simple
