title:  Pauls fern, in front of mature alder on the Windfall Trail
lat:  47.556604
lon:  -122.251273
firstReported: 2018
lastUpdate:  2019-03-31
radius:  5
area: 10
severity: 10
notesFile: notes.html
photoTabs:
  - title: 1/12/19
    url: https://lh3.googleusercontent.com/a_dW1uKU1crRXMyj6K2j7KJbg-X0768gAg_MWrh3Frw78nswVPDwdsYKzGSr0RvGZ4jmqKmOrct8ycssnSk86tL-UplJUHaREpSwqaasxDZf1fjJ0fsWw0DTC9hbxfLT9xKg99EExZM=w2400
  - title: 3/24
    url: https://lh3.googleusercontent.com/FaEcuPT3B6o5_iBzFJZ68cFCFcjAcAGP7YHmPaqg2XsXiNpzf2iE8zkbG7PuLkTMd4WVrkbZUb593PGWC4NYx6J3hAeSNQaV0Y5XAm0PdsV4OI7g6yhKSOjtayd7FQLLHlQC0BNBH0Q=w2400
  - title: 3/31
    url: https://lh3.googleusercontent.com/WCtg9wqFAV8Qyy7xnPMvNOAcTGLMOcT-01A-UagBD9sx4rAT4mPUaPoaq6TwGYHuHcw77N_wIRQfZp6db6U-vUEqUc9xkRghFiXozwtFaFxOhKESUjN3RJFQS71fcUwuzvFltI84JNU=w2400

