area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 6-02,2018
lastUpdate: 6-02,2018
lat: 47.5310016
lon: -122.0064277
notesFile: ''
radius: 10.0
severity: 2
text: 'bunch of dead above trail.50? plus along swamp trail '
title: 'tiger mountain swamp trail: bunch of dead above trail.50? plus along swamp
  trail'
type: rectangle
