area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 9-24, 2019
lastUpdate: 9-24, 2019
lat: 47.6058493
lon: -121.9871325
notesFile: ''
radius: 10.0
severity: 1
text: a couple dead. checked out mounds of moss at least one covered sword fern stubble.
  nort trail.?
title: 'soaring eagle: a couple dead. checked out mounds of moss at least one covered
  sword fern stubble.'
type: rectangle
