area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-12, 2018
lastUpdate: 10-12, 2018
lat: 47.5305271
lon: -122.0232546
notesFile: ''
radius: 10.0
severity: 3
text: '"1000+ dead sword ferns counted so far on trails: swamp 450, big tree 100,plateau
  lake 200, school? 150, brink 150." '
title: 'tiger mountain: 1000+ dead sword ferns counted so far on trails: swamp 450,
  big tree 100,plateau lake 200, school? 150, brink 150.'
type: rectangle
