area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 9-15,2018
lastUpdate: 9-15,2018
lat: 47.5958531
lon: -122.167769
notesFile: ''
radius: 10.0
severity: 2
text: 20 plus dead vs a couple a year ago. bellevue
title: 'mctavish woodridge: 20 plus dead vs a couple a year ago.'
type: rectangle
