area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.59188000319936
lon: -122.2271352733366
notesFile: notes.html
radius: 100
severity: 0
text: about 20 dead in area. maybe planted. Al Smith Field Report 29
title: 20 dead
type: simple
