area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 9-27,2017
lastUpdate: 9-27,2017
lat: 47.6034801
lon: -122.1126515
notesFile: ''
radius: 10.0
severity: 2
text: '"s, sw" '
title: 'weowena park: s, sw'
type: rectangle
