area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.58549528979501
lon: -122.2886310766213
notesFile: notes.html
radius: 100
severity: 0
text: 50+ dead in park, at least some planted. 16 dead in vicinity. Al Smith Field
  Report 50
title: '>50 dead'
type: simple
