area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 11-17, 2018
lastUpdate: 11-17, 2018
lat: 47.5275237
lon: -122.1182724
notesFile: ''
radius: 10.0
severity: 1
text: 10 or so dead in area including 3 near knapsack which might have been brushed
  to death.last picture shows one unhealthy looking sword fern. sky country trail
title: 'cougar mountain: 10 or so dead in area including 3 near knapsack which might
  have been brushed to death.last picture shows one unhealthy looking sword fern.'
type: rectangle
