area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10 -07, 2018
lastUpdate: 10 -07, 2018
lat: 47.5829176
lon: -122.2252268
notesFile: ''
radius: 10.0
severity: 2
text: about 25 dead. jumped over the ridge and into east ravine. few reduced to stubble
  as of now. mercer island
title: 'upper luther burbank park: about 25 dead. jumped over the ridge and into east
  ravine. few reduced to stubble as of now.'
type: rectangle
