area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: august 18, 2019
lastUpdate: august 18, 2019
lat: 47.5929042
lon: -122.2267148
notesFile: ''
radius: 10.0
severity: 1
text: 20 or so dead in restoration project between two trails mercer island
title: 'luther burbank: 20 or so dead in restoration project between two trails'
type: rectangle
