area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.60548373608372
lon: -122.1770184210158
notesFile: notes.html
radius: 100
severity: 0
text: Alex Wright, botanist was aware of the die off in garden and wilburton hill
  before I took first photopoint. many dead elsewhere in the garden. Al Smith Field
  Report 60
title: garden site
type: simple
