area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.56089816019799
lon: -122.2541052496006
notesFile: notes.html
radius: 100
severity: 0
text: knapsack in middle of 4 dead stubble sword ferns first noticed in 2014. Al Smith
  Field Report 52
title: 4 dead
type: simple
