area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-07,2017
lastUpdate: 10-07,2017
lat: 47.6512193
lon: -122.1699199
notesFile: ''
radius: 10.0
severity: 1
text: '"s, w" bellevue'
title: 'bridal trails: s, w'
type: rectangle
