area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: may 6 2018
lastUpdate: may 6 2018
lat: 47.5283091
lon: -122.2630257
notesFile: ''
radius: 10.0
severity: 1
text: 'south '
title: 'prit chard beach: south'
type: rectangle
