area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: august 22, 2019
lastUpdate: august 22, 2019
lat: 47.5791191
lon: -122.2159959
notesFile: ''
radius: 10.0
severity: 1
text: 10 or so dead upstream continuing beyond other side of bridge. perhaps most
  concerning is a number of sickly appearing ferns.  mercer island
title: 'gallagher hills open space: 10 or so dead upstream continuing beyond other
  side of bridge. perhaps most concerning is a number of sickly appearing ferns. '
type: rectangle
