area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 11-01, 2019
lastUpdate: 11-01, 2019
lat: 47.5457684
lon: -122.3472798
notesFile: ''
radius: 10.0
severity: 1
text: 25 or so dead in about an area 100 feet by 100 feet. many others sickly looking
  green. others struggling but with fronds with attenuated pinae. restor seattle
title: 'west duwamish greenbelt: 25 or so dead in about an area 100 feet by 100 feet.
  many others sickly looking green. others struggling but with fronds with attenuated
  pinae. restor'
type: rectangle
