area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: ''
lastUpdate: ''
lat: 47.5188415
lon: -122.160924
notesFile: ''
radius: 10.0
severity: 1
text: 'about ten dead '
title: 'may creek: about ten dead'
type: rectangle
