area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 9-19, 2018
lastUpdate: 9-19, 2018
lat: 47.5535855
lon: -122.2152592
notesFile: ''
radius: 10.0
severity: 2
text: 83 plus dead in area. mercer island
title: 'se 53rd open space.: 83 plus dead in area.'
type: rectangle
