area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 5-03, 2019
lastUpdate: 5-03, 2019
lat: 47.5384382
lon: -121.9986544
notesFile: ''
radius: 10.0
severity: 1
text: 22 dead to this point mostly along paved path. here 50+ dead along both sides
  of trail. coal mine loop trail
title: 'issaquah highlands?: 22 dead to this point mostly along paved path. here 50+
  dead along both sides of trail.'
type: rectangle
