area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: august 22, 2019
lastUpdate: august 22, 2019
lat: 47.5550207
lon: -122.2140266
notesFile: ''
radius: 10.0
severity: 2
text: '"counted over 110 dead. many still are dying, acer mac leaves no problem in
  seeing dead ferns." mercer island'
title: 'se 53rd st oprn space: counted over 110 dead. many still are dying, acer mac
  leaves no problem in seeing dead ferns.'
type: rectangle
