area: 10
color: red
contact: ''
firstReported: ''
lastUpdate: ''
lat: 47.55851
lon: -122.2842
notesFile: notes.html
radius: 30
severity: 0
text: My seven-year-old goddaughter and I sit in a café, more than a mile from Seward Park, but still holding Sqebeqsed in mind.
title: Empire Espresso
type: simple
