area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 6-08, 2018
lastUpdate: 6-08, 2018
lat: 47.5833578
lon: -122.2255341
notesFile: ''
radius: 10.0
severity: 2
text: '"over 100 dead, but unlike north mercerdale not many new dead in last year
  and one half" upper luther burbank'
title: 'mercerisland: over 100 dead, but unlike north mercerdale not many new dead
  in last year and one half'
type: rectangle
