area: 10
color: orange
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.730882
lon: -121.414558
notesFile: notes.html
radius: 100
severity: 0
text: Rural ornamental garden, complete die-off of ~50 plants
title: Baring, Forest Residence
type: simple
