area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.52879448336844
lon: -122.007243883206
notesFile: notes.html
radius: 100
severity: 0
text: 60 plus dead in area. Al Smith Field Report 16
title: '>60 dead'
type: simple
