area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.53474812669187
lon: -122.007526025895
notesFile: notes.html
radius: 100
severity: 0
text: 140+ dead on brink trail including 70+ in patch a couple hundred feet beyond
  first patch of 50+. Al Smith Field Report 31
title: '>140 dead'
type: simple
