area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 5-08, 2019
lastUpdate: 5-08, 2019
lat: 47.5402682
lon: -122.1503922
notesFile: ''
radius: 10.0
severity: 2
text: 37 + dead in area another 13 dead from ymca coal creek
title: 'trail alongside newcastle golf club road: 37 + dead in area another 13 dead
  from ymca'
type: rectangle
