area: 2
color: orange
borderColor: orange
contact: Paul Shannon
firstReported: '2010-01-01'
lastUpdate: '2019-03-28'
lat: 47.701276
lon: -122.583528
notesFile: notes.html
radius: 100
severity: 3
text: Two acres, private second-growth forest, first report in the region, 2010
title: Sandy Hook Road
type: circle
photoTabs:
  - title: April 2017
    url: https://lh3.googleusercontent.com/56unZLrv9LEcafvoAMfMDkEjR5jJNnXGUHhcF0_h19sArknGjR5XQwB2ISmj_nSxxohlG8UD_DeJ7mFGctgaCstR2qIVNuVilaASc-G6mUxRHMWzO8-bUBVMAILHfujRQ0lzoPYE4ZY=w2400
videoTabs:
   - title: 4/17 video site survey
     url: https://www.youtube.com/embed/uC38AX3aeRo



