area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 7-29, 2018
lastUpdate: 7-29, 2018
lat: 47.7107728
lon: -122.2483052
notesFile: ''
radius: 10.0
severity: 1
text: '"nw, e" kirkland'
title: 'o.o. denny: nw, e'
type: rectangle
