# source ~/github/slexil/tests/pshannon-py363/bin/activate

default: 
	python ../regen.py . stories.html

publish:
	scp stories.html paulshannnon@pshannon.net:public_html/pshannon.net/sewardParkStories/index.html
	open http://pshannon.net/sewardParkStories




