area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 9-28, 2018
lastUpdate: 9-28, 2018
lat: 47.557927
lon: -122.374224
notesFile: ''
radius: 10.0
severity: 1
text: '"a few dead along 100 feet of trail, but 15 more near dead" seattle'
title: 'camp long: a few dead along 100 feet of trail, but 15 more near dead'
type: rectangle
