area: 2
color: red
contact: Paul Shannon
firstReported: '2019-06-05'
lastUpdate: '2019-06-05'
lat: 47.86584
lon: -122.84311
notesFile: notes.html
radius: 400
severity: 5
text: Penney and Michael's property, site 2, lower forest. All sites combined - 30 acres.
title: Quilcence site number 2, lower, forested
type: simple



