area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.506151596031
lon: -122.0855741346248
notesFile: notes.html
radius: 100
severity: 0
text: 35 dead along road to just a little beyond this point.some back up in woods,
  59+ dead so far. Al Smith Field Report 46
title: 35 dead
type: simple
