area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: july 18,2018
lastUpdate: july 18,2018
lat: 47.699983
lon: -122.0537335
notesFile: ''
radius: 10.0
severity: 2
text: '"87 dead to this point. here about 15 dead, but are mostly moss cove" '
title: 'redmond watershed: 87 dead to this point. here about 15 dead, but are mostly
  moss cove'
type: rectangle
