area: 10
color: orange
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.74727
lon: -122.51289
notesFile: notes.html
radius: 100
severity: 0
text: 'February, 2019: large area, dead ferns, reported by John Oleary'
title: IPT1
type: simple
