area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.52800100317045
lon: -122.0701828932215
notesFile: notes.html
radius: 100
severity: 0
text: more dead, about 22 in area. Al Smith Field Report 39
title: 22 dead
type: simple
