area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 12-02, 2018
lastUpdate: 12-02, 2018
lat: 47.5419594
lon: -122.1504647
notesFile: ''
radius: 10.0
severity: 2
text: '"about 50 dead, some not visible buried by fallen Acer mac leaves. still not
  much different from initial photopoint." bellevue'
title: 'coal creek: about 50 dead, some not visible buried by fallen Acer mac leaves.
  still not much different from initial photopoint.'
type: rectangle
