area: 1
color: red
borderColor: red
contact: Caleb Goldstein-Miller
firstReported: '2019-06-17'
lastUpdate: '2019-06-17'
lat: 47.592794
lon: -122.114915
notesFile: notes.html
radius: 400
severity: 5
text: In a grove of large cedars. Originally reported by Al Smith?
title: Weowna Park Trails
type: circle



