area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 9-22, 2017
lastUpdate: 9-22, 2017
lat: 47.5332301
lon: -122.1278508
notesFile: ''
radius: 10.0
severity: 2
text: '"east, southeast" '
title: 'cougar: east, southeast'
type: rectangle
