area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 5-05, 2019
lastUpdate: 5-05, 2019
lat: 47.6286831
lon: -122.2966068
notesFile: ''
radius: 10.0
severity: 2
text: '"about 34+ dead just uphill from path, many struggling to put up fiddleheads."
  road-path west of japanese garden'
title: 'arboretum: about 34+ dead just uphill from path, many struggling to put up
  fiddleheads.'
type: rectangle
