area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: tmarch 02, 2018
lastUpdate: tmarch 02, 2018
lat: 47.585294
lon: -122.2883542
notesFile: ''
radius: 10.0
severity: 1
text: sw coleman
title: 'seattle: sw'
type: rectangle
