area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-20, 2018
lastUpdate: 10-20, 2018
lat: 47.5146284
lon: -122.0838633
notesFile: ''
radius: 10.0
severity: 2
text: 114 dead or more along length of trail. a couple areas of ten or more. cougar
  mountain
title: 'squeak mountain connector trail: 114 dead or more along length of trail. a
  couple areas of ten or more.'
type: rectangle
