area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 5-30, 2019
lastUpdate: 5-30, 2019
lat: 47.3961491
lon: -122.043239
notesFile: ''
radius: 10.0
severity: 1
text: '"counted 2 dead to this point, but here along 30'' of trail counted 37 dead."
  renton to landsberg. 17 miles ?'
title: 'cedar river trail: counted 2 dead to this point, but here along 30 of trail
  counted 37 dead.'
type: rectangle
