area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 'march 11, 1019 '
lastUpdate: 'march 11, 1019 '
lat: 47.5964409
lon: -122.5225327
notesFile: ''
radius: 10.0
severity: 1
text: maybe 10 or so dead  in area. bainbridge
title: 'port blakely -fort ward trail: maybe 10 or so dead  in area.'
type: rectangle
