area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 11-28, 2018
lastUpdate: 11-28, 2018
lat: 47.5549185
lon: -122.214057
notesFile: ''
radius: 10.0
severity: 2
text: '"Samsung tab, better pictures? better gps? only  counted about 70 dead, but
  probably many crowns buried under fallen Acer mac leaves." mercer island'
title: 'Seward 53rd st open space: Samsung tab, better pictures? better gps? only  counted
  about 70 dead, but probably many crowns buried under fallen Acer mac leaves.'
type: rectangle
