area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.55485769993568
lon: -122.2475838775735
notesFile: notes.html
radius: 100
severity: 0
text: lots of dead sword ferns and not many skunk cabbages still visible. Al Smith
  Field Report 51
title: dead ferns and skunk cabbages
type: simple
