area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.49897360980456
lon: -122.1835376797724
notesFile: notes.html
radius: 100
severity: 0
text: about 50 dead, some not visible buried by fallen Acer mac leaves. still not
  much different from initial photopoint. Al Smith Field Report 58
title: 50 dead
type: simple
