area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.41
lon: -123.32
notesFile: notes.html
radius: 100
severity: 0
text: 'April 2019: some sickly, dying, and dead sword ferns, no fiddlehead ... [in]
  a very rural area without a great deal of human impact. There is an abandoned road
  grade which elk evidently use in the immediate area; perhaps the elk carried the
  pathogen in on their hooves. '
title: Near Brown Creek Campground, off Forest Road 2340
type: simple
