area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 9-23,2017
lastUpdate: 9-23,2017
lat: 47.5357687
lon: -122.1299281
notesFile: ''
radius: 10.0
severity: 2
text: '"south, southeast" '
title: ' coal creek: south, southeast'
type: rectangle
