area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 1-02, 2019
lastUpdate: 1-02, 2019
lat: 47.5637362
lon: -122.2997072
notesFile: ''
radius: 10.0
severity: 2
text: '"45+ dead along a couple hundred feet of trail and 30 feet to either side.
  many more, perhaps a quarter more appear to be dying." seattle'
title: '  cheasty boulevard greenspace: 45+ dead along a couple hundred feet of trail
  and 30 feet to either side. many more, perhaps a quarter more appear to be dying.'
type: rectangle
