area: 1
color: red
contact: Paul Shannon
firstReported: '2019-06-05'
lastUpdate: '2019-06-05'
lat: 47.86667
lon: -122.84097
notesFile: notes.html
radius: 400
severity: 5
text: Penney and Michael's property, site 1, upper clearing.  All sites combined - 30 acres.
title: Quilcence site Number 1
type: simple



