area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.55185859638883
lon: -122.1538900128564
notesFile: notes.html
radius: 100
severity: 0
text: 20 or more dead in area. along the trail others looking sickly. Al Smith Field
  Report 49
title: 20 dead
type: simple
