area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-17, 2018
lastUpdate: 10-17, 2018
lat: 47.5316408
lon: -122.0842251
notesFile: ''
radius: 10.0
severity: 3
text: 247 dead along trail. many others looking poorly. just a couple dead at this
  photopoint. bear ridge trail to junction with tibbets creek trail
title: 'cougar mountain: 247 dead along trail. many others looking poorly. just a
  couple dead at this photopoint.'
type: rectangle
