area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.587326
lon: -122.525978
notesFile: notes.html
radius: 100
severity: 0
text: 7500 sq.ft. December 2017
title: Trail between Fort Ward and Blakeley Harbor Parks
type: simple
