area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.53163509352912
lon: -122.0842103129424
notesFile: notes.html
radius: 100
severity: 0
text: 247 dead along trail. many others looking poorly. just a couple dead at this
  photopoint. Al Smith Field Report 37
title: 247 dead
type: simple
