area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-16, 2018
lastUpdate: 10-16, 2018
lat: 47.3690291
lon: -122.1381207
notesFile: ''
radius: 10.0
severity: 2
text: '"another 20 dead or so on other side, east side of trail." '
title: 'soos creek: another 20 dead or so on other side, east side of trail.'
type: rectangle
