area: 10
color: orange
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.857426
lon: -122.049626
notesFile: notes.html
radius: 100
severity: 0
text: 'January 2018, Snohomish Parks staff: ''We hiked to a much larger site that
  showed signs of complete sword fern mortality that looked like it was spreading
  radially. The ground  at that site was barren, and the brown fronds were spreading
  to surrounding plants.'''
title: Lord Hill Regional Park
type: simple
