area: 1
color: red
borderColor: red
contact: Caleb Goldstein-Miller
firstReported: '2019-06-05'
lastUpdate: '2019-06-05'
lat: 47.71022
lon: -122.24929
notesFile: notes.html
radius: 400
severity: 5
text: In St. Edwards' State Park?
title: Denny Creek Trailhead
type: circle



