area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: march 11, 2019
lastUpdate: march 11, 2019
lat: 47.5973087
lon: -122.519563
notesFile: ''
radius: 10.0
severity: 1
text: lots of sickly looking from blakely hill intersection to this point. about 20
  dead here mostly stubble blakely harbor
title: 'bainbridge island: lots of sickly looking from blakely hill intersection to
  this point. about 20 dead here mostly stubble'
type: rectangle
