area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-16,2018
lastUpdate: 10-16,2018
lat: 47.3675577
lon: -122.143704
notesFile: ''
radius: 10.0
severity: 2
text: '"New device, better pictures. counted 50+ dead sword ferns" '
title: 'soos creek: New device, better pictures. counted 50+ dead sword ferns'
type: rectangle
