area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 8-16,2018
lastUpdate: 8-16,2018
lat: 47.59577
lon: -122.1675715
notesFile: ''
radius: 10.0
severity: 1
text: '"20 plus dead ln area. 2 or 3 previously- October 13, 2017." bellevue'
title: 'mcavish: 20 plus dead ln area. 2 or 3 previously- October 13, 2017.'
type: rectangle
