area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.50920995300584
lon: -122.2491365220084
notesFile: notes.html
radius: 100
severity: 0
text: photo depicts steep se facing slope,  some completely dead ferns among healthy.  Mature
  acma [Big Leaf Maple] forest Al Smith Field Report 1
title: Dead Horse Canyon
type: simple
