area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.51650756845974
lon: -122.2802849028598
notesFile: notes.html
radius: 100
severity: 0
text: '10 or more dead along an eroded bank along 75'' or so of side walk.attachment
  #5 sword fern above not looking too good. Al Smith Field Report 59'
title: 10 dead
type: simple
