area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 9-15, 2018
lastUpdate: 9-15, 2018
lat: 47.5663852
lon: -122.2119229
notesFile: ''
radius: 10.0
severity: 2
text: about 40 plus dead along some 150 feet of embankment. mercer island
title: 'east mercer way: about 40 plus dead along some 150 feet of embankment.'
type: rectangle
