area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-20, 2018
lastUpdate: 10-20, 2018
lat: 47.5553381
lon: -122.1032012
notesFile: ''
radius: 10.0
severity: 2
text: about 30 dead so far. 8+ dead in area. bellevue
title: 'lakemont: about 30 dead so far. 8+ dead in area.'
type: rectangle
