area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 6/28/17
lastUpdate: 6/28/17
lat: 47.5613208
lon: -122.2981241
notesFile: ''
radius: 10.0
severity: 1
text: On edge of social trail "4701 Mountain View Dr S, Seattle, WA 98108"
title: 'Cheasty Mt View: On edge of social trail'
type: rectangle
