area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-31, 2019
lastUpdate: 10-31, 2019
lat: 47.5192773
lon: -122.2824507
notesFile: ''
radius: 10.0
severity: 1
text: now about 16 dead in area seattle
title: 'east duwamish greenbelt: now about 16 dead in area'
type: rectangle
