area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 5-28, 2019
lastUpdate: 5-28, 2019
lat: 47.5610491
lon: -122.2541413
notesFile: ''
radius: 10.0
severity: 2
text: '"saw 3 or 4 dead sword ferns as early as 2014-2015. now many more in site where
  last year i saw one maiden hair fern, but this year lots of dead sword " seattle'
title: 'seward park: saw 3 or 4 dead sword ferns as early as 2014-2015. now many more
  in site where last year i saw one maiden hair fern, but this year lots of dead sword '
type: rectangle
