area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-13, 2018
lastUpdate: 10-13, 2018
lat: 47.5927886
lon: -122.1151253
notesFile: ''
radius: 10.0
severity: 3
text: 100+ dead now on both sides of trail. previously about 30 dead.  bellevue
title: '   weona park: 100+ dead now on both sides of trail. previously about 30 dead. '
type: rectangle
