area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-17, 2018
lastUpdate: 10-17, 2018
lat: 47.5280067
lon: -122.0701977
notesFile: ''
radius: 10.0
severity: 2
text: '"more dead, about 22 in area." '
title: 'cougar-talus open space: more dead, about 22 in area.'
type: rectangle
