area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 5-08, 2019
lastUpdate: 5-08, 2019
lat: 47.5415405
lon: -122.1509416
notesFile: ''
radius: 10.0
severity: 2
text: '50 dead recorded sept 2017. this time including area adjacent to maintenance
  road.120 + dead not including many sickly looking lacking fiddleheads. '
title: 'coal creek park: 50 dead recorded sept 2017. this time including area adjacent
  to maintenance road.120 + dead not including many sickly looking lacking fiddleheads.'
type: rectangle
