area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 9-14,2018
lastUpdate: 9-14,2018
lat: 47.6112664
lon: -122.2835222
notesFile: ''
radius: 10.0
severity: 2
text: '15 or so dead within 50 uptrail and downstream. '
title: 'madrona woods, seattle: 15 or so dead within 50 uptrail and downstream.'
type: rectangle
