area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 9-29,2017
lastUpdate: 9-29,2017
lat: 47.6113912
lon: -122.283494
notesFile: ''
radius: 10.0
severity: 1
text: '"se, sw" '
title: 'madrona woods: se, sw'
type: rectangle
