area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.64398177707056
lon: -122.052464156162
notesFile: notes.html
radius: 100
severity: 0
text: about 15 dead in area. Al Smith Field Report 41
title: 15 dead
type: simple
