area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 11-28, 2018
lastUpdate: 11-28, 2018
lat: 47.5827655
lon: -122.2258815
notesFile: ''
radius: 10.0
severity: 1
text: going for better GPS point. 20+ dead in immediate area and all reveal evidence
  of pathogen straying into east ravine. mercer island
title: 'upper luther burbank park: going for better GPS point. 20+ dead in immediate
  area and all reveal evidence of pathogen straying into east ravine.'
type: rectangle
