area: 1
color: red
borderColor: red
contact: Caleb Goldstein-Miller
firstReported: '2019-06-25'
lastUpdate: '2019-06-25'
lat: 47.847857
lon: -122.048754
notesFile: notes.html
radius: 400
severity: 3
text: 
title: Lord Hill Die-off 2
type: circle



