area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 5-20, 2019
lastUpdate: 5-20, 2019
lat: 47.520419
lon: -121.9888374
notesFile: ''
radius: 10.0
severity: 1
text: 'dead sword fern at 1400 feet. maybe uppermost of 150 dead? '
title: 'west tiger mountain trail: dead sword fern at 1400 feet. maybe uppermost of
  150 dead?'
type: rectangle
