area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.585615056319
lon: -122.2393136012266
notesFile: notes.html
radius: 100
severity: 0
text: about 100 dead, Al Smith Field Report 10
title: 100 dead
type: simple
