area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 6-15, 2018
lastUpdate: 6-15, 2018
lat: 47.524347
lon: -122.0235243
notesFile: ''
radius: 10.0
severity: 2
text: '"trail to round lake, hopefully. about 80 dead so far" "trail to round lake,
  maybe."'
title: 'issaquah: trail to round lake, hopefully. about 80 dead so far'
type: rectangle
