area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 5-20, 2019
lastUpdate: 5-20, 2019
lat: 47.5153578
lon: -121.9873788
notesFile: ''
radius: 10.0
severity: 2
text: 'about upper limit of sword ferns at 2200 feet. 150 dead ferns scattered about
  along trail but no more after about 1600 feet. '
title: 'west tiger mountain: about upper limit of sword ferns at 2200 feet. 150 dead
  ferns scattered about along trail but no more after about 1600 feet.'
type: rectangle
