area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: march 10, 2019
lastUpdate: march 10, 2019
lat: 47.5431495
lon: -122.1488351
notesFile: ''
radius: 10.0
severity: 1
text: 24 dead to this point from coal creekparkway trail head at least 25 more dead
  in this area.many stubble or just crowns. bellevue
title: 'coal creek plus primrose trail: 24 dead to this point from coal creekparkway
  trail head at least 25 more dead in this area.many stubble or just crowns.'
type: rectangle
