area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 11-09, 2018
lastUpdate: 11-09, 2018
lat: 47.5548634
lon: -122.2475987
notesFile: ''
radius: 10.0
severity: 2
text: lots of dead sword ferns and not many skunk cabbages still visible. south skunk
  cabbage patch
title: 'Seward park: lots of dead sword ferns and not many skunk cabbages still visible.'
type: rectangle
