area: 1
color: red
contact: Caleb Goldstein-Miller
firstReported: '2019-06-25'
lastUpdate: '2019-06-25'
lat: 47.532344
lon: -122.006808 
notesFile: notes.html
radius: 400
severity: 5
text: One of several sites on Tiger and Cougar Mountains
title: Tiger Mt. Swamp Trail Die Off 1 (TMD1)
type: simple



