area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 6-08, 2018
lastUpdate: 6-08, 2018
lat: 47.5856207
lon: -122.2393284
notesFile: ''
radius: 10.0
severity: 2
text: about 100 dead north mercerdale
title: 'mercer island: about 100 dead'
type: rectangle
