area: 1
color: red
borderColor: red
contact: Caleb Goldstein-Miller
firstReported: '2019-06-19'
lastUpdate: '2019-06-19'
lat: 47.337007
lon: -123.309368
notesFile: notes.html
radius: 400
severity: 2
text: Ferns with late unfurled chlorotic new growth fronds lacking sori
title: NF-24 (near Vance Creek Viaduct trailhead)
type: circle



