area: 10
color: orange
borderColor: orange
contact: ''
firstReported: '2017-12-01'
lastUpdate: '2017-12-01'
lat: 47.587326
lon: -122.525978
notesFile: notes.html
radius: 100
severity: 2
text: 7500 sq.ft. December 2017
title: Trail between Fort Ward and Blakeley Harbor Parks
type: circle
