area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: '11-14, 2018 '
lastUpdate: '11-14, 2018 '
lat: 47.5316535
lon: -122.396992
notesFile: ''
radius: 10.0
severity: 1
text: '"Sharon said ivy removed. stubble ferns moss covered killed by ivy?some ferns
  exhibiting an unhealthy looking yellowish green, as in last photo." west seattle'
title: 'lincoln: Sharon said ivy removed. stubble ferns moss covered killed by ivy?some
  ferns exhibiting an unhealthy looking yellowish green, as in last photo.'
type: rectangle
