area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: april 28,2019
lastUpdate: april 28,2019
lat: 47.6964485
lon: -122.0559697
notesFile: ''
radius: 10.0
severity: 2
text: '"55 dead to this point 20+ dead in area many moss covered crowns.190 + dead
  trout loop trail, 50+ dead trillium connecter, 20+ dead mostly start of tre" trout
  loop trail'
title: 'redmond watershed preserve: 55 dead to this point 20+ dead in area many moss
  covered crowns.190 + dead trout loop trail, 50+ dead trillium connecter, 20+ dead
  mostly start of tre'
type: rectangle
