area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.233074
lon: -122.856873
notesFile: notes.html
radius: 100
severity: 0
text: September, 2018
title: Hartstene Island, near Fudge Point.
type: simple
