area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 5-23, 2019
lastUpdate: 5-23, 2019
lat: 47.5142052
lon: -122.0914345
notesFile: ''
radius: 10.0
severity: 1
text: area in picture and along creek has 20+ dead "and whittaker trails , cougar
  mountain"
title: 'junction of nawang gombu wilderness cliffs trail a: area in picture and along
  creek has 20+ dead'
type: rectangle
