area: 1
color: red
contact: Caleb Goldstein-Miller
firstReported: '2019-06-10'
lastUpdate: '2019-06-10'
lat: 45.47261
lon: -122.27543
notesFile: notes.html
radius: 400
severity: 5
text: A consequence of spraying? right at the start of the trail by the road.
title: Sandy River Gorge Secret Trail
type: simple



