area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 5- 30, 2019
lastUpdate: 5- 30, 2019
lat: 47.2743691
lon: -122.0194039
notesFile: ''
radius: 10.0
severity: 1
text: '"2 dead in attachment 2, 20 or so dead scattered along 100'' of trail." green
  river'
title: 'flaming geyser state park: 2 dead in attachment 2, 20 or so dead scattered
  along 100 of trail.'
type: rectangle
