area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.52751804085312
lon: -122.118257649685
notesFile: notes.html
radius: 100
severity: 0
text: 10 or so dead in area including 3 near knapsack which might have been brushed
  to death.last picture shows one unhealthy looking sword fern. Al Smith Field Report
  54
title: 10 dead
type: simple
