area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 11-28, 2018
lastUpdate: 11-28, 2018
lat: 47.5917964
lon: -122.2271334
notesFile: ''
radius: 10.0
severity: 1
text: this time counted 30+ dead in area. mercer island
title: 'luther burbank park: this time counted 30+ dead in area.'
type: rectangle
