area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 6-02, 2018
lastUpdate: 6-02, 2018
lat: 47.5319269
lon: -122.0140537
notesFile: ''
radius: 10.0
severity: 1
text: about 20 dead in area issaquah
title: 'tiger mountain big tree trail: about 20 dead in area'
type: rectangle
