area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-13, 2018
lastUpdate: 10-13, 2018
lat: 47.6034163
lon: -122.1126175
notesFile: ''
radius: 10.0
severity: 2
text: '"about 84 dead in area. so far 2 big areas of die-off, 2 smaller areas of less
  than 20 dead each and some scattered adding to about 250 dead." just off Sammamish
  parkway'
title: 'weona park: about 84 dead in area. so far 2 big areas of die-off, 2 smaller
  areas of less than 20 dead each and some scattered adding to about 250 dead.'
type: rectangle
