area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 12-02, 2018
lastUpdate: 12-02, 2018
lat: 47.5357614
lon: -122.1298786
notesFile: ''
radius: 10.0
severity: 2
text: covered with Acer mac leaves but a few more sickly looking ferns. hard to count
  number of dead. bellevue
title: 'coal creek: covered with Acer mac leaves but a few more sickly looking ferns.
  hard to count number of dead.'
type: rectangle
