area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 1-13, 2019
lastUpdate: 1-13, 2019
lat: 47.7105192
lon: -122.2476307
notesFile: ''
radius: 10.0
severity: 1
text: '"about 7 dead in immediate vicinity, but others looking very sick indeed. 20+
  dead in area." juanita'
title: 'o.o Denny park: about 7 dead in immediate vicinity, but others looking very
  sick indeed. 20+ dead in area.'
type: rectangle
