area: 1
color: red
contact: Caleb Goldstein-Miller
firstReported: '2019-06-05'
lastUpdate: '2019-06-05'
lat: 47.696636
lon: -122.050549
notesFile: notes.html
radius: 400
severity: 5
text: 
title: Redmond Watershed Preserve Die-off 2
type: simple



