area: 10
color: red
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.53236
lon: -122.007313
notesFile: notes.html
radius: 100
severity: 0
text: 400 dead ferns along 1 mile of the trail (14 mar 2019), Al Smith
title: Tiger Mountain Swamp Trail
type: simple
