area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.36755197652074
lon: -122.1436892494968
notesFile: notes.html
radius: 100
severity: 0
text: New device, better pictures. counted 50+ dead sword ferns. Al Smith Field Report
  35
title: '>50 dead'
type: simple
