area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.50416198165451
lon: -122.0910660701997
notesFile: notes.html
radius: 100
severity: 0
text: 8 or so dead in area. another 20 or so scattered along .1 mile trail to redtown
  dam. Al Smith Field Report 53
title: 8 plus 20 nearby
type: simple
