area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.69667711652929
lon: -122.0517520832564
notesFile: notes.html
radius: 100
severity: 0
text: 30 dead or so at beginning of trail. 116 dead trout loop trail. Al Smith Field
  Report 13
title: 30 at trail start, 116 on loop trail
type: simple
