area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.36609771230285
lon: -122.1396838854142
notesFile: notes.html
radius: 100
severity: 0
text: 30 plus dead  sword ferns.just a couple. Al Smith Field Report 17
title: '> 30 dead'
type: simple
