title:  Seward Park Ground Zero
lat: 47.555474
lon: -122.248945
radius:  100
severity: 10
summaryTextFile: overview.html
photoTabs:
  - title: "Before and After:  2011 2017"
    url: https://4.bp.blogspot.com/-xpU4_m8AXW0/WhjplTnA2hI/AAAAAAAAX64/n_GNVcM0E1E8xE3EgrJAvjgi5b37nsO6wCLcBGAs/s1600/Screen%2BShot%2B2017-11-24%2Bat%2B7.54.16%2BPM.png
  - title: Lazarus Fern
    url: "https://2.bp.blogspot.com/-0u1aT9PEBcI/WqtEkMgaQOI/AAAAAAAAX_0/ailkJiE1w6oCvsCXbcipTvhho6rDiGNWACLcBGAs/s1600/IMG_2057.JPG"
videoTabs:
   - title: KING 5 News 2017
     url: https://youtu.be/qtifUa6LTn4



