area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.53490204254159
lon: -122.013351439406
notesFile: notes.html
radius: 100
severity: 0
text: 50+ dead sword ferns along and about 50' of trail. Al Smith Field Report 30
title: '>50 dead'
type: simple
