area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 9-07,2018
lastUpdate: 9-07,2018
lat: 47.5248898
lon: -122.1431032
notesFile: ''
radius: 10.0
severity: 1
text: '"about 15 dead in area another 30 or so on wildside, de leo and marshalls hill
  trail." de leo trail or close by'
title: 'cougar: about 15 dead in area another 30 or so on wildside, de leo and marshalls
  hill trail.'
type: rectangle
