area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 9-26,2017
lastUpdate: 9-26,2017
lat: 47.5639922
lon: -122.3000387
notesFile: ''
radius: 10.0
severity: 1
text: '"northwest ,southwesthuguq" '
title: 'cheasty: northwest ,southwesthuguq'
type: rectangle
