area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.55491285033582
lon: -122.214042233113
notesFile: notes.html
radius: 100
severity: 0
text: Samsung tab, better pictures? better gps? only  counted about 70 dead, but probably
  many crowns buried under fallen Acer mac leaves. Al Smith Field Report 57
title: 70 dead
type: simple
