area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 10-31, 2019
lastUpdate: 10-31, 2019
lat: 47.520142
lon: -122.2820071
notesFile: ''
radius: 10.0
severity: 1
text: about 10 dead up hillside seattle
title: 'east duwamish greenbelt: about 10 dead up hillside'
type: rectangle
