area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 8-16, 2018
lastUpdate: 8-16, 2018
lat: 47.5288002
lon: -122.0072586
notesFile: ''
radius: 10.0
severity: 2
text: '60 plus dead in area '
title: 'tradittion lke yrail: 60 plus dead in area'
type: rectangle
