area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.69997725002186
lon: -122.0537187252145
notesFile: notes.html
radius: 100
severity: 0
text: 87 dead to this point. here about 15 dead, but are mostly moss cove. Al Smith
  Field Report 14
title: 87 dead
type: simple
