area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 5-23, 2019
lastUpdate: 5-23, 2019
lat: 47.5121404
lon: -122.0893122
notesFile: ''
radius: 10.0
severity: 1
text: 24 dead to this point. 4 dead in picture. 104 dead along length of whittaker
  trail. cougar mountain
title: 'jim whitaker trail: 24 dead to this point. 4 dead in picture. 104 dead along
  length of whittaker trail.'
type: rectangle
