area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.52488406658871
lon: -122.1430884667681
notesFile: notes.html
radius: 100
severity: 0
text: about 15 dead in area another 30 or so on wildside, de leo and marshalls hill
  trail. Al Smith Field Report 20
title: 15 plus 30 nearby
type: simple
