area: 10
color: blue
contact: ''
firstReported: '2000-01-01'
lastUpdate: '2000-01-01'
lat: 47.54576026951687
lon: -122.07436700034
notesFile: notes.html
radius: 100
severity: 0
text: counted 8 dead may 18, 2018 up to shangra la trail. obviously missed seeing
  these 16. + crowns and stubble covered with moss. Al Smith Field Report 63
title: 8 dead
type: simple
