area: 1
color: red
contact: Caleb Goldstein-Miller
firstReported: '2018-08-01'
lastUpdate: '2019-06-06'
lat: 47.41236
lon: -123.32217
notesFile: notes.html
radius: 400
severity: 5
text:  At the start of the trail leading away from the Brown Creek campground water pump.
title: Brown Creek Campground, Olympic National Forest
type: simple



