default: restoration

restoration:
	(cd ..; python regen.py sewardRestoration sewardRestoration/sewardRestoration.html)

publish:
	scp sewardRestoration.html paulshannnon@pshannon.net:public_html/pshannon.net/maps/

