area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 9-24, 2019
lastUpdate: 9-24, 2019
lat: 47.6018738
lon: -121.9796545
notesFile: ''
radius: 10.0
severity: 1
text: 'ten dead at start of trail '
title: 'soaring eagle: ten dead at start of trail'
type: rectangle
