title:  Seward Park Kingfisher Point
lat: 47.554852
lon: -122.254974
radius:  10
severity: 1
photoTabs:
   1:
      title: me
      url: https://www.systemsbiology.org/wp-content/uploads/paul-shannon-web-300x300.jpg
videoTabs:
   1:
      title: composting at seward park
      url: https://youtu.be/vG4vr83Ffd4



