area: 0.0
color: blue
borderColor: blue
contact: Al Smith
firstReported: 6/28/17
lastUpdate: 6/28/17
lat: 47.5614003
lon: -122.2975255
notesFile: ''
radius: 10.0
severity: 1
text: Off trail on ridge east of bowl "4701 Mountain View Dr S, Seattle, WA 98108"
title: 'Cheasty Mt View: Off trail on ridge east of bowl'
type: rectangle
