default:
	python ../regen.py ../regional.2020 regional.2020.html
	open regional.2020.html
venv:
	@echo source /Users/paul/github/slexil/tests/pshannon-py363/bin/activate

publish:
	scp regional.2020.html paulshannnon@pshannon.net:public_html/pshannon.net/swordFerns/regionalMap/2020.html
	open http://pshannon.net/swordFerns/regionalMap/2020.html

