default:
	python ../regen.py ../regional.2020 regional.2020.html

publish:
	scp regional.2020.html paulshannnon@pshannon.net:public_html/pshannon.net/swordFerns/regionalMap/2020.html
	open http://pshannon.net/swordFerns/regionalMap/2020.html

